### ISSUE TITLE
插件有毒，小心导入

### ISSUE THREAD

**Issue by liyang0207** [miaozhang9/wecharCodejar#2]
这jar中有几个很蛋疼的插件，恶心了我一下午，自己之前定义的插件习惯全乱了，webstorm一打开就要输入什么api key，拜托做插件的时候能不能纯净点，自己的setting就不要放出去了

**Comment by zhishaofei3** [comment]
肯定啊 这一看就是所有的setting 你自己的设置都没了

**Comment by pb-cheung** [comment]
@liyang0207 @zhishaofei3 
我看了下并不是所有配置，仅是动态模板（Live Templates）部分配置，但还是可能会覆盖自己配置。
使用更好的方法：https://github.com/pbestz/blog/issues/8

**Comment by toutoumu** [comment]
这些都可以自己配置的, 我配置了好几百个live templates

**Comment by bluecats7** [comment]
妈的，把我的设置也覆盖了，sB

**Comment by Timo-coder-jeby** [comment]
垃圾
